stages:
 - build
 - release

build:windows:
  stage: build
  tags:
  - windows
  when: manual
  script:
    - choco install -y cmake --installargs '"ADD_CMAKE_TO_PATH=System"'
    - $env:Path += ";C:\Program Files\CMake\bin"
    - cmake . -DCMAKE_TOOLCHAIN_FILE="windows-x86.cmake"
    - cmake --build . --config Release
    - cp Release/$CI_PROJECT_NAME.dll ./

  after_script:
    - $env = "windows_x86_JOB_ID=$CI_JOB_ID"
    - Add-Content -Path job.env -Value $env
  artifacts:
    name: $CI_PROJECT_NAME
    paths:
    - $CI_PROJECT_NAME.dll
    expire_in: never
    reports:
       dotenv: job.env
    
release:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  when: manual
  needs: [build:windows]
  variables:
    TAG: '0.1'
  script:
    - echo "Create Release $TAG"
  release:
    tag_name: '$TAG'
    description: "./CHANGELOG.md"
    assets:
      links:
        - name: "$CI_PROJECT_NAME.dll"
          url: "$CI_PROJECT_URL/-/jobs/$windows_x86_JOB_ID/artifacts/download"
          link_type: "package"
